### PR TITLE
Enable relative loading of assets for pystage-generated .py files.

### PR DESCRIPTION
**Pull request by ahlongxp**
Previously, pystage loaded assets from the current directories or the pkg directory. This commit introduces the ability to load assets from any location by dynamically adding search directories relative to the location of the pystage-generated .py file. With this change, pystage-generated .py files can smoothly load assets and run from different directories.

After the merge, errors like this should disappear:
```
ahlongxp@ZacWorkBook sbs % python move6/move.py 
New costume: _1 -> /Users/ahlongxp/coding/pystage/src/pystage/images/zombie_idle.png
New costume: _1_2 -> /Users/ahlongxp/coding/pystage/src/pystage/images/zombie_idle.png
New costume: _2 -> /Users/ahlongxp/coding/pystage/src/pystage/images/zombie_idle.png
Traceback (most recent call last):
  File "/Users/ahlongxp/coding/sbs/move6/move.py", line 18, in <module>
    _1.add_sound('a_bass')
  File "/Users/ahlongxp/coding/pystage/src/pystage/en/sprite.py", line 1752, in add_sound
    return self._core.pystage_addsound(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlongxp/coding/pystage/src/pystage/core/_sound.py", line 23, in pystage_addsound
    self.sound_manager.add_sound(name)
  File "/Users/ahlongxp/coding/pystage/src/pystage/core/assets.py", line 196, in add_sound
    sound = Sound(self, name)
            ^^^^^^^^^^^^^^^^^
  File "/Users/ahlongxp/coding/pystage/src/pystage/core/assets.py", line 223, in __init__
    if self.file.endswith(".mp3"):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

### CODE REVIEW

**Comment by kaiec** [comment]
Thank you for the PR and sorry for the late response :-) This is a good addition, but the check for len > 0 is not needed, sys.argv always contains at least one element. I will modify the PR and merge.
